
name: Deploy Applications on TEST

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: self-hosted

    steps:
    - name: 'Checkout repository'
      run: |
        /home/djodzo/run.sh
        /home/djodzo/runBE.sh
