name: Publish Nginx

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Checkout frontend
      uses: actions/checkout@v3
      with:
        repository: dently-ai/dentlyai-frontend
        path: scripts/frontend
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: 'Build and push FRONTEND image'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        cd scripts/frontend
        docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/frontend:test
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/frontend:test
    
    - name: 'Build and push NGINX image'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        cd scripts/nginx
        docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/nginx:test
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/nginx:test
